/*
  Data layer for the AI Tooling Landscape Map / Capability Register / Measurement Dashboard.

  Evidence rules (see prompt):
  - Do not invent Skyscanner tools, owners, approvals, usage figures, costs, or results.
  - Where information is unavailable, use clearly labelled placeholders.
  - All example records are clearly marked as EXAMPLE and must not be presented as real tools.
*/

// ---------------------------------------------------------------------------
// Lifecycle model
// ---------------------------------------------------------------------------

const LIFECYCLE_COLUMNS = ["Source", "Create", "Review", "Deliver", "Learn"];

const LIFECYCLE_DEFINITIONS = {
  Source: "Backpack tokens, components, patterns, standards, rules, customer insights, and other authoritative inputs.",
  Create: "Design, research, content, prototyping, code, and AI-assisted creation.",
  Review: "Human judgement and automated validation.",
  Deliver: "Pull requests, tickets, handoffs, experiments, and production gates.",
  Learn: "Usage, quality, customer impact, business impact, and iteration.",
};

const WORKFLOW_ROWS = [
  "Strategy and opportunity discovery",
  "Research and insight synthesis",
  "Ideation and concept development",
  "Content and interaction design",
  "UI creation and prototyping",
  "Design-system discovery and use",
  "Design-to-code",
  "Accessibility and quality validation",
  "Experiment definition and delivery",
  "Documentation and collaboration",
  "Measurement and learning",
];

const CROSS_CUTTING_LAYERS = [
  { label: "Backpack and authoritative inputs", note: "Confirmed connection required for any capability that touches the design system." },
  { label: "Ownership and decision rights", note: "Owner to confirm where not yet named." },
  { label: "Privacy and security", note: "Approval status unknown until reviewed." },
  { label: "Accessibility", note: "No evidence collected for most capabilities yet." },
  { label: "Provenance and traceability", note: "Baseline required to assess coverage." },
  { label: "Human-review requirements", note: "Assumption: human review is required unless confirmed otherwise." },
  { label: "Reversibility and rollback", note: "Data source to identify for rollback approach." },
  { label: "Measurement and evidence", note: "See Measurement Dashboard for current evidence state." },
];

// ---------------------------------------------------------------------------
// Connected workstreams
// Strategic/organisational classification (orthogonal to the workflow x
// lifecycle matrix). Sourced from the "Ten commitments, four connected
// workstreams" model - not invented here. Each capability record can carry a
// primary workstream and, optionally, a secondary connection.
// ---------------------------------------------------------------------------

const WORKSTREAMS = {
  systems: { id: "01", label: "System foundations", shortLabel: "Systems", colorClass: "workstream--systems" },
  capability: { id: "02", label: "Design capability", shortLabel: "Capability", colorClass: "workstream--capability" },
  delivery: { id: "03", label: "Governed delivery", shortLabel: "Delivery", colorClass: "workstream--delivery" },
  practice: { id: "04", label: "Practice and pipeline", shortLabel: "Practice", colorClass: "workstream--practice" },
};

// ---------------------------------------------------------------------------
// Capability type
// A separate, orthogonal classification from "connected workstream"
// (strategic ownership) and workflow/lifecycle position (where in the
// process). This answers "what kind of thing is this?" so that skills,
// training, automations, agents, and tools are not all lumped into one
// undifferentiated "tool" bucket.
//
// Decision guide:
// 1. Is it a human ability rather than a system? -> skill.
//    Is it the mechanism that builds that ability? -> training.
// 2. Otherwise, does it run/execute?
//    No -> reference/rule -> standard. Behaviour/ritual -> process.
//    Yes -> has its own name/UI -> aiTool. Bolted onto another tool -> aiFeature.
//    Invisible underlying asset -> infrastructure.
//    Fixed sequence -> automation. Dynamically decides its own steps -> agent.
// ---------------------------------------------------------------------------

const CAPABILITY_TYPES = {
  aiTool: { label: "AI tool / product", icon: "◆", description: "A distinct, separately named AI-assisted product with its own UI." },
  aiFeature: { label: "AI feature", icon: "◇", description: "An AI capability embedded inside a broader, otherwise non-AI tool." },
  automation: { label: "Automation / workflow", icon: "▤", description: "A defined, repeatable sequence of steps that executes the same way each time." },
  agent: { label: "Agent / assistant", icon: "▣", description: "A semi-autonomous system that decides its own next steps within a task." },
  skill: { label: "Skill / competency", icon: "★", description: "A human capability - something a person can do." },
  training: { label: "Training / enablement", icon: "☆", description: "The structured mechanism (course, workshop, certification) that builds a skill." },
  process: { label: "Process / ritual", icon: "●", description: "A non-tool operating practice or behaviour." },
  standard: { label: "Standard / guideline", icon: "▲", description: "An authoritative rule, policy, or reference document." },
  infrastructure: { label: "Infrastructure / model asset", icon: "▦", description: "An underlying technical asset (model, dataset, index) other capabilities depend on." },
};

// ---------------------------------------------------------------------------
// Enumerations (status, maturity, portfolio action, evidence)
// ---------------------------------------------------------------------------

const APPROVAL_STATUSES = {
  approved: { label: "Approved", icon: "✓", tone: "positive" },
  restricted: { label: "Restricted", icon: "⚠", tone: "caution" },
  pilot: { label: "Pilot", icon: "◐", tone: "info" },
  experimental: { label: "Experimental", icon: "✦", tone: "info" },
  underInvestigation: { label: "Under investigation", icon: "?", tone: "neutral" },
  notApproved: { label: "Not approved", icon: "✕", tone: "negative" },
  unknown: { label: "Unknown", icon: "–", tone: "unknown" },
};

const MATURITY_STAGES = [
  "Identified",
  "Assessing",
  "Piloting",
  "Validated",
  "Scaling",
  "Established",
  "Retiring",
];

const PORTFOLIO_ACTIONS = {
  scale: "Scale",
  integrate: "Integrate",
  improve: "Improve",
  pilot: "Pilot",
  consolidate: "Consolidate",
  retire: "Retire",
  investigate: "Investigate",
};

const EVIDENCE_STATES = {
  none: { label: "No evidence", icon: "○" },
  anecdotal: { label: "Anecdotal", icon: "◔" },
  earlySignal: { label: "Early signal", icon: "◑" },
  workflowImpact: { label: "Measured workflow impact", icon: "◕" },
  qualityImpact: { label: "Measured quality impact", icon: "◕" },
  businessImpact: { label: "Measured business impact", icon: "●" },
};

// ---------------------------------------------------------------------------
// Capability records
// Field groups follow the register structure (Identity / Need & use /
// Portfolio state / Ownership / Governance / Evidence), reduced to the
// "essential first-version fields" plus a few enrichment fields.
// ---------------------------------------------------------------------------

const CAPABILITIES = [
  {
    id: "REG-001",
    isExample: true,
    name: "EXAMPLE - Research synthesis capability",
    description: "Illustrative capability for turning raw qualitative research into structured themes and insights.",
    role: "Owner to confirm",
    jobToBeDone: "Turn raw interview/survey data into structured, traceable insight themes",
    workflowStage: "Research and insight synthesis",
    lifecycleColumn: "Create",
    connectedWorkstream: "capability",
    secondaryWorkstream: null,
    approvalStatus: "underInvestigation",
    maturity: "Assessing",
    owner: "Owner to confirm",
    backpackConnection: "Not applicable / to confirm",
    evidence: "anecdotal",
    principalRisk: "Provenance of synthesised themes not yet traceable to source data",
    recommendedAction: "Investigate",
    lastReviewed: "No evidence collected",
  },
  {
    id: "REG-002",
    isExample: true,
    name: "EXAMPLE - UI generation capability",
    description: "Illustrative capability for AI-assisted generation of UI screens or components from a prompt or brief.",
    role: "Product designer",
    jobToBeDone: "Rapidly draft UI options for a known flow before manual refinement",
    workflowStage: "UI creation and prototyping",
    lifecycleColumn: "Create",
    connectedWorkstream: "systems",
    secondaryWorkstream: "capability",
    approvalStatus: "pilot",
    maturity: "Piloting",
    owner: "Owner to confirm",
    backpackConnection: "Approval status unknown",
    evidence: "earlySignal",
    principalRisk: "Generated UI may bypass Backpack components/tokens",
    recommendedAction: "Pilot",
    lastReviewed: "Baseline required",
  },
  {
    id: "REG-003",
    isExample: true,
    name: "EXAMPLE - Accessibility validation capability",
    description: "Illustrative capability for automated accessibility checks against WCAG 2.2 AA on design or code artefacts.",
    role: "Accessibility reviewer",
    jobToBeDone: "Catch accessibility issues earlier in the design/review stage",
    workflowStage: "Accessibility and quality validation",
    lifecycleColumn: "Review",
    connectedWorkstream: "delivery",
    secondaryWorkstream: null,
    approvalStatus: "unknown",
    maturity: "Identified",
    owner: "Owner to confirm",
    backpackConnection: "Data source to identify",
    evidence: "none",
    principalRisk: "False negatives could give unwarranted confidence in compliance",
    recommendedAction: "Investigate",
    lastReviewed: "No evidence collected",
  },
  {
    id: "REG-004",
    isExample: false,
    isUnconfirmed: true,
    name: "Design Radar - feedback and review tool",
    description: "Indexes Figma files and lets teams request or give structured feedback, including an AI-generated review summary, before work moves into delivery. Organised into team spaces (e.g. Backpack, Flights, Hotels, Falcon · SEO, AI lab).",
    role: "Product designer / design reviewer",
    jobToBeDone: "Get faster, structured feedback on design work before it ships",
    workflowStage: "Documentation and collaboration",
    lifecycleColumn: "Review",
    connectedWorkstream: "delivery",
    secondaryWorkstream: "capability",
    approvalStatus: "unknown",
    maturity: "Piloting",
    owner: "Owner to confirm",
    backpackConnection: "Approval status unknown",
    evidence: "anecdotal",
    principalRisk: "AI review summary accuracy and provenance not yet validated",
    recommendedAction: "Investigate",
    lastReviewed: "Observed via screenshot - not yet confirmed with tool owner",
  },
  {
    id: "REG-005",
    isExample: false,
    name: "Signal - challenges assumptions and missing evidence in briefs",
    description: "Reviews a product brief and surfaces unstated assumptions and missing evidence before work moves into ideation.",
    role: "Product designer / strategist",
    jobToBeDone: "Pressure-test a brief's assumptions and evidence base before committing design effort",
    workflowStage: "Strategy and opportunity discovery",
    lifecycleColumn: "Review",
    connectedWorkstream: null,
    secondaryWorkstream: null,
    approvalStatus: "experimental",
    maturity: "Piloting",
    owner: "Choon Hui",
    backpackConnection: "Not applicable / to confirm",
    evidence: "anecdotal",
    principalRisk: "Beta skill; scope, approval, and reliability of assumption-checking not yet validated",
    recommendedAction: "Pilot",
    lastReviewed: "Listed as a beta on the Design skills page; not yet confirmed with a broader evidence source.",
  },
  {
    id: "REG-006",
    isExample: false,
    name: "Backpack-docs - answers component and foundation questions",
    description: "Answers questions about Backpack components and foundations, linked to a repository.",
    role: "Product designer / engineer",
    jobToBeDone: "Get an authoritative answer about a Backpack component or foundation without searching docs manually",
    workflowStage: "Design-system discovery and use",
    lifecycleColumn: "Source",
    connectedWorkstream: null,
    secondaryWorkstream: null,
    approvalStatus: "unknown",
    maturity: "Identified",
    owner: "Laura Gutierrez",
    backpackConnection: "Direct - answers questions against Backpack components and foundations",
    evidence: "anecdotal",
    principalRisk: "Accuracy and currency of answers against the live Backpack library not yet validated",
    recommendedAction: "Investigate",
    lastReviewed: "Shared skill with a repository link on the Design skills page; not yet confirmed with a broader evidence source.",
  },
  {
    id: "REG-007",
    isExample: false,
    name: "Backpack-Skill-Layout",
    description: "Generates Backpack layouts from guidance shared as a skill.",
    role: "Product designer",
    jobToBeDone: "Generate a Backpack-compliant layout starting point instead of building one from scratch",
    workflowStage: "UI creation and prototyping",
    lifecycleColumn: "Create",
    connectedWorkstream: null,
    secondaryWorkstream: null,
    approvalStatus: "unknown",
    maturity: "Identified",
    owner: "Raquel Machin",
    backpackConnection: "Direct - generates Backpack layouts",
    evidence: "anecdotal",
    principalRisk: "Generated layouts may not stay aligned with the latest Backpack components/tokens",
    recommendedAction: "Investigate",
    lastReviewed: "Shared guidance for generating Backpack layouts on the Design skills page; not yet confirmed with a broader evidence source.",
  },
  {
    id: "REG-008",
    isExample: false,
    name: "Backpack Ark UI component-creation",
    description: "Documented workflow for creating Backpack components from Ark UI.",
    role: "Product designer / engineer",
    jobToBeDone: "Follow a repeatable workflow to turn an Ark UI primitive into a Backpack component",
    workflowStage: "Design-to-code",
    lifecycleColumn: "Create",
    connectedWorkstream: null,
    secondaryWorkstream: null,
    approvalStatus: "unknown",
    maturity: "Identified",
    owner: "Raquel Machin",
    backpackConnection: "Direct - produces Backpack components",
    evidence: "anecdotal",
    principalRisk: "Consistency of output against Backpack component standards not yet validated at scale",
    recommendedAction: "Investigate",
    lastReviewed: "Documented component-creation workflow on the Design skills page; not yet confirmed with a broader evidence source.",
  },
  {
    id: "REG-009",
    isExample: false,
    name: "Design-heuristics",
    description: "Shared guidance for generating design work against recognised heuristics.",
    role: "Product designer",
    jobToBeDone: "Apply recognised design heuristics while generating new design work",
    workflowStage: "Content and interaction design",
    lifecycleColumn: "Create",
    connectedWorkstream: null,
    secondaryWorkstream: null,
    approvalStatus: "unknown",
    maturity: "Identified",
    owner: "Owner to confirm",
    backpackConnection: "Not applicable / to confirm",
    evidence: "anecdotal",
    principalRisk: "Which heuristics are applied and how consistently is not yet documented",
    recommendedAction: "Investigate",
    lastReviewed: "Shared guidance for generation and prototype audits on the Design skills page; not yet confirmed with a broader evidence source.",
  },
  {
    id: "REG-010",
    isExample: false,
    name: "Design-heuristics",
    description: "Shared guidance for auditing prototypes against recognised design heuristics.",
    role: "Product designer",
    jobToBeDone: "Audit a prototype against recognised design heuristics before it moves forward",
    workflowStage: "Content and interaction design",
    lifecycleColumn: "Review",
    connectedWorkstream: null,
    secondaryWorkstream: null,
    approvalStatus: "unknown",
    maturity: "Identified",
    owner: "Owner to confirm",
    backpackConnection: "Not applicable / to confirm",
    evidence: "anecdotal",
    principalRisk: "Which heuristics are applied and how consistently is not yet documented",
    recommendedAction: "Investigate",
    lastReviewed: "Shared guidance for generation and prototype audits on the Design skills page; not yet confirmed with a broader evidence source.",
  },
  {
    id: "REG-011",
    isExample: false,
    name: "Web typography",
    description: "Shared skill for creating web typography.",
    role: "Product designer",
    jobToBeDone: "Set up web typography that follows established conventions while drafting a design",
    workflowStage: "UI creation and prototyping",
    lifecycleColumn: "Create",
    connectedWorkstream: null,
    secondaryWorkstream: null,
    approvalStatus: "unknown",
    maturity: "Identified",
    owner: "Owner to confirm",
    backpackConnection: "Approval status unknown",
    evidence: "anecdotal",
    principalRisk: "Relationship to Backpack typography tokens not yet confirmed",
    recommendedAction: "Investigate",
    lastReviewed: "Shared typography creation and review skill on the Design skills page; not yet confirmed with a broader evidence source.",
  },
  {
    id: "REG-012",
    isExample: false,
    name: "Web typography",
    description: "Shared skill for reviewing web typography.",
    role: "Product designer",
    jobToBeDone: "Review a design's typography against established conventions",
    workflowStage: "UI creation and prototyping",
    lifecycleColumn: "Review",
    connectedWorkstream: null,
    secondaryWorkstream: null,
    approvalStatus: "unknown",
    maturity: "Identified",
    owner: "Owner to confirm",
    backpackConnection: "Approval status unknown",
    evidence: "anecdotal",
    principalRisk: "Relationship to Backpack typography tokens not yet confirmed",
    recommendedAction: "Investigate",
    lastReviewed: "Shared typography creation and review skill on the Design skills page; not yet confirmed with a broader evidence source.",
  },
  {
    id: "REG-013",
    isExample: false,
    name: "Content-review",
    description: "Checks writing against Backpack content guidance and tone of voice.",
    role: "UX writer / content designer",
    jobToBeDone: "Check copy against Backpack content guidelines and tone of voice before it ships",
    workflowStage: "Content and interaction design",
    lifecycleColumn: "Review",
    connectedWorkstream: null,
    secondaryWorkstream: null,
    approvalStatus: "unknown",
    maturity: "Identified",
    owner: "Owner to confirm",
    backpackConnection: "Direct - checks against Backpack content guidance and tone of voice",
    evidence: "anecdotal",
    principalRisk: "Usage and accuracy of the automated check not yet measured",
    recommendedAction: "Investigate",
    lastReviewed: "Confirmed via code in the content-review plugin repository; usage not yet measured.",
  },
  {
    id: "REG-014",
    isExample: false,
    name: "Accessibility assist",
    description: "One of three accessibility skills; answers accessibility questions and surfaces relevant guidance.",
    role: "Product designer / accessibility reviewer",
    jobToBeDone: "Get grounded accessibility guidance (WCAG, ARIA, Backpack behaviour) while working",
    workflowStage: "Accessibility and quality validation",
    lifecycleColumn: "Source",
    connectedWorkstream: null,
    secondaryWorkstream: null,
    approvalStatus: "experimental",
    maturity: "Assessing",
    owner: "Owner to confirm",
    backpackConnection: "Approval status unknown",
    evidence: "none",
    principalRisk: "Adoption and effectiveness remain unverified",
    recommendedAction: "Investigate",
    lastReviewed: "Listed as available in September per Slack discussion; repository excerpts confirm the plugin, but adoption and effectiveness are unverified.",
  },
  {
    id: "REG-015",
    isExample: false,
    name: "Accessibility detect",
    description: "One of three accessibility skills; scans local code changes for accessibility failures.",
    role: "Engineer / product designer",
    jobToBeDone: "Catch accessibility failures in a diff before raising a PR",
    workflowStage: "Accessibility and quality validation",
    lifecycleColumn: "Review",
    connectedWorkstream: null,
    secondaryWorkstream: null,
    approvalStatus: "experimental",
    maturity: "Assessing",
    owner: "Owner to confirm",
    backpackConnection: "Approval status unknown",
    evidence: "none",
    principalRisk: "Adoption and effectiveness remain unverified",
    recommendedAction: "Investigate",
    lastReviewed: "Listed as available in September per Slack discussion; repository excerpts confirm the plugin, but adoption and effectiveness are unverified.",
  },
  {
    id: "REG-016",
    isExample: false,
    name: "Accessibility fix",
    description: "One of three accessibility skills; suggests accessibility code fixes as reviewable diffs.",
    role: "Engineer / product designer",
    jobToBeDone: "Get a reviewable accessibility fix for a known finding instead of writing it from scratch",
    workflowStage: "Accessibility and quality validation",
    lifecycleColumn: "Create",
    connectedWorkstream: null,
    secondaryWorkstream: null,
    approvalStatus: "experimental",
    maturity: "Assessing",
    owner: "Owner to confirm",
    backpackConnection: "Approval status unknown",
    evidence: "none",
    principalRisk: "Adoption and effectiveness remain unverified",
    recommendedAction: "Investigate",
    lastReviewed: "Listed as available in September per Slack discussion; repository excerpts confirm the plugin, but adoption and effectiveness are unverified.",
  },
  {
    id: "REG-017",
    isExample: false,
    name: "CSV Survey Analysis",
    description: "Analyses survey CSV exports, including built-in significance testing.",
    role: "Researcher",
    jobToBeDone: "Analyse a survey export, including significance testing, without manual spreadsheet work",
    workflowStage: "Research and insight synthesis",
    lifecycleColumn: "Create",
    connectedWorkstream: null,
    secondaryWorkstream: null,
    approvalStatus: "pilot",
    maturity: "Piloting",
    owner: "Owner to confirm",
    backpackConnection: "Not applicable / to confirm",
    evidence: "anecdotal",
    principalRisk: "Statistical methodology and provenance of significance tests not independently reviewed",
    recommendedAction: "Pilot",
    lastReviewed: "Actual use reported by Research in the September research update.",
  },
  {
    id: "REG-018",
    isExample: false,
    isUnconfirmed: true,
    name: "AI-assisted qualitative analysis and research write-ups",
    description: "Reported working practice for using AI assistance in qualitative analysis and research write-ups, rather than one named standalone tool.",
    role: "Researcher",
    jobToBeDone: "Speed up qualitative analysis and write-up drafting with AI assistance",
    workflowStage: "Research and insight synthesis",
    lifecycleColumn: "Create",
    connectedWorkstream: null,
    secondaryWorkstream: null,
    approvalStatus: "unknown",
    maturity: "Assessing",
    owner: "Owner to confirm",
    backpackConnection: "Not applicable / to confirm",
    evidence: "anecdotal",
    principalRisk: "No single named tool to govern; practice-level provenance and review requirements undefined",
    recommendedAction: "Investigate",
    lastReviewed: "Reported as a working practice in the September research update, not a named standalone tool.",
  },
  {
    id: "REG-019",
    isExample: false,
    name: "ClaudeOS - transcript filing, project context and action tracking",
    description: "Shared local workflow for filing transcripts, holding project context, and tracking actions.",
    role: "Individual practitioner (personal workflow)",
    jobToBeDone: "Keep transcripts, project context, and action items organised locally across sessions",
    workflowStage: "Documentation and collaboration",
    lifecycleColumn: "Create",
    connectedWorkstream: null,
    secondaryWorkstream: null,
    approvalStatus: "experimental",
    maturity: "Assessing",
    owner: "Jamie Ford",
    backpackConnection: "Not applicable / to confirm",
    evidence: "anecdotal",
    principalRisk: "Personal/local workflow; governance, data handling, and support model not yet defined",
    recommendedAction: "Investigate",
    lastReviewed: "Shared local workflow on the Design skills page, with a colleague reporting use; not yet confirmed with a broader evidence source.",
  },
  {
    id: "REG-020",
    isExample: false,
    name: "Create-PR skill",
    description: "Implemented Hotels Web workflow for opening templated pull requests.",
    role: "Engineer (Hotels Web)",
    jobToBeDone: "Open a correctly templated PR without assembling it by hand",
    workflowStage: "Design-to-code",
    lifecycleColumn: "Deliver",
    connectedWorkstream: null,
    secondaryWorkstream: null,
    approvalStatus: "unknown",
    maturity: "Assessing",
    owner: "Owner to confirm",
    backpackConnection: "Not applicable / to confirm",
    evidence: "none",
    principalRisk: "Designer access to this engineering-facing workflow is not established",
    recommendedAction: "Investigate",
    lastReviewed: "Confirmed via code evidence in the Hotels Web coding-skills repository; designer access not established.",
  },
  {
    id: "REG-021",
    isExample: false,
    name: "Dr. Jekyll experiment skill",
    description: "Repository skill for creating experiments.",
    role: "Engineer (Hotels Web)",
    jobToBeDone: "Set up an experiment definition without starting from a blank template",
    workflowStage: "Experiment definition and delivery",
    lifecycleColumn: "Deliver",
    connectedWorkstream: null,
    secondaryWorkstream: null,
    approvalStatus: "unknown",
    maturity: "Identified",
    owner: "Owner to confirm",
    backpackConnection: "Not applicable / to confirm",
    evidence: "none",
    principalRisk: "Runtime operation not tested; behaviour in a live experiment pipeline is unverified",
    recommendedAction: "Investigate",
    lastReviewed: "Confirmed via code evidence in the Hotels Web workflow-automation repository; runtime operation not tested.",
  },
  {
    id: "REG-022",
    isExample: false,
    name: "Skyfinder experiment analysis",
    description: "Team-specific skill analysing experiment metrics and producing a ship/no-ship recommendation.",
    role: "Geo team analyst",
    jobToBeDone: "Turn experiment metrics into a ship/no-ship recommendation without manual analysis",
    workflowStage: "Measurement and learning",
    lifecycleColumn: "Learn",
    connectedWorkstream: null,
    secondaryWorkstream: null,
    approvalStatus: "pilot",
    maturity: "Piloting",
    owner: "Owner to confirm",
    backpackConnection: "Not applicable / to confirm",
    evidence: "earlySignal",
    principalRisk: "Team-specific scope; generalisability of the recommendation logic beyond Geo not yet assessed",
    recommendedAction: "Pilot",
    lastReviewed: "Confirmed via code evidence in the Geo compass-toolkit repository.",
  },
  {
    id: "REG-023",
    isExample: false,
    isUnconfirmed: true,
    name: "Research AI success-metrics tracking",
    description: "Existing measurement practice tracking AI success metrics for the research function; supporting measurement infrastructure rather than an AI agent.",
    role: "Research operations",
    jobToBeDone: "Track whether AI use in research is actually delivering value",
    workflowStage: "Measurement and learning",
    lifecycleColumn: "Learn",
    connectedWorkstream: null,
    secondaryWorkstream: null,
    approvalStatus: "unknown",
    maturity: "Assessing",
    owner: "Owner to confirm",
    backpackConnection: "Not applicable / to confirm",
    evidence: "anecdotal",
    principalRisk: "Measurement infrastructure, not an AI agent; should not be portfolio-managed as a tool",
    recommendedAction: "Investigate",
    lastReviewed: "September survey of 12 respondents, reported in the September research update.",
  },
  {
    id: "REG-024",
    isExample: false,
    name: "Deceptive design auditor",
    description: "Draft Claude skill (deceptive-design-audit, v0.2) that audits Skyscanner UI designs and flows for deceptive/dark patterns against DSA Article 25, producing severity-rated findings and a Clear / Advisory / Action required / Blocked verdict. Planned to become a sub-agent within a central validation framework owned by the Enable team.",
    role: "Product designer / compliance reviewer",
    jobToBeDone: "Assess a UI design or flow for deceptive design patterns before it ships, ahead of DSA Article 25 obligations",
    workflowStage: "Accessibility and quality validation",
    lifecycleColumn: "Review",
    connectedWorkstream: null,
    secondaryWorkstream: null,
    approvalStatus: "experimental",
    maturity: "Assessing",
    owner: "Clare Holmes, Josh Thomson, Jo Wilson (deceptive design working group)",
    backpackConnection: "Not applicable / to confirm",
    evidence: "anecdotal",
    principalRisk: "Draft taxonomy and severity criteria not yet ratified by the working group; orchestration, audit-store integration, and output schema depend on the Enable team's central validation agent, which does not yet exist",
    recommendedAction: "Pilot",
    lastReviewed: "Documented in the DSA Compliance space (skill definition v0.2 and 'Back brief: deceptive design') by the deceptive design working group; not yet piloted or integrated with a central validation agent.",
  },
];

// Empty template, mirrors the register's essential fields, used for the
// "add a new capability" row/template.
const EMPTY_CAPABILITY_TEMPLATE = {
  id: "REG-___",
  isExample: false,
  isTemplate: true,
  name: "Tool to validate",
  description: "",
  role: "Owner to confirm",
  jobToBeDone: "",
  workflowStage: "",
  lifecycleColumn: "",
  connectedWorkstream: null,
  secondaryWorkstream: null,
  approvalStatus: "unknown",
  maturity: "Identified",
  owner: "Owner to confirm",
  backpackConnection: "Approval status unknown",
  evidence: "none",
  principalRisk: "",
  recommendedAction: "Investigate",
  lastReviewed: "No evidence collected",
};

// ---------------------------------------------------------------------------
// Measurement dashboard
// The strategy linkage records the department outcome, Product Design strategy,
// enabling conditions, and the distinction between direct enablement and shared
// business contribution. Every measure remains a clearly labelled placeholder
// until its definition, baseline, owner, and source are confirmed.
// ---------------------------------------------------------------------------

const DEPARTMENT_OUTCOME = "Make good design easier to create, validate and scale.";

const STRATEGY_LINKAGES = [
  {
    goal: "Faster, higher-quality Product Design",
    strategy: "AI-native ways of working",
    conditions: ["AI-native", "Cultural", "Structural"],
    signals: ["Approved AI-tool enablement", "AI capability development plans", "Governed tool adoption"],
    leadingMeasures: ["Designers actively using approved AI tools", "Designers with an AI capability development plan", "Time from kick-off to first prototype"],
    outcomeMeasures: ["Prototype-to-successful-XP cycle time", "Rework or quality measures"],
    attribution: "Design Infrastructure enables the conditions; downstream product impact requires shared evidence.",
  },
  {
    goal: "Faster delivery with less bespoke UI",
    strategy: "Backpack and scalable contribution model",
    conditions: ["Structural", "Cultural", "AI-native"],
    signals: ["Atlas gaps prioritised", "Contribution-model throughput", "Backpack adoption in AI-assisted outputs"],
    leadingMeasures: ["Atlas gaps usable in Backpack", "Components through the contribution model", "Backpack adoption in AI-assisted outputs"],
    outcomeMeasures: ["Bespoke UI reduction in priority teams", "Delivery speed", "Quality consistency"],
    attribution: "Requires product and engineering adoption data.",
  },
  {
    goal: "Design shapes roadmaps and committed bets",
    strategy: "Strategic direction",
    conditions: ["Strategic", "Structural", "Cultural"],
    signals: ["Design-led ideas in flight", "Evidence entering roadmap decisions", "Reusable ideas across CX"],
    leadingMeasures: ["Design-led novel product ideas in flight", "Evidence entering roadmap decisions", "Reusable ideas across CX"],
    outcomeMeasures: ["Ideas shipped with positive KPI impact", "Speed of acting on validated scalable ideas"],
    attribution: "Business KPI impact is a contribution measure, not proof of direct causation.",
  },
];

const SCORECARD_GROUPS = [
  {
    group: "Adoption and capability",
    strategy: "AI-native ways of working",
    indicators: [
      {
        outcome: "Designers actively using approved AI tools",
        current: "Data unavailable",
        target: "Contextual target: >90% (definition, baseline, population to confirm)",
        trend: "Not yet measurable",
        confidence: "Unknown",
        evidence: "Baseline required",
        owner: "Owner to confirm",
        commentary: "No data source identified yet for active usage.",
      },
      {
        outcome: "Designers with an AI capability development plan",
        current: "Data unavailable",
        target: "Contextual target: >90% (connected to AI capabilities roadmap)",
        trend: "Not yet measurable",
        confidence: "Unknown",
        evidence: "Definition required",
        owner: "Owner to confirm",
        commentary: "Development plan definition not yet confirmed.",
      },
    ],
  },
  {
    group: "Workflow and velocity",
    strategy: "AI-native ways of working",
    indicators: [
      {
        outcome: "Time from kick-off to first prototype",
        current: "Data unavailable",
        target: "Target to confirm",
        trend: "Not yet measurable",
        confidence: "Unknown",
        evidence: "No data source",
        owner: "Owner to confirm",
        commentary: "No comparison group established yet.",
      },
      {
        outcome: "Rework rate on AI-assisted outputs",
        current: "Data unavailable",
        target: "Target to confirm",
        trend: "Not yet measurable",
        confidence: "Unknown",
        evidence: "Undefined metric",
        owner: "Owner to confirm",
        commentary: "Metric definition pending.",
      },
    ],
  },
  {
    group: "Quality and scale",
    strategy: "Backpack and scalable contribution model",
    indicators: [
      {
        outcome: "Backpack adoption in AI-assisted outputs",
        current: "Data unavailable",
        target: "Target to confirm",
        trend: "Not yet measurable",
        confidence: "Unknown",
        evidence: "No data source",
        owner: "Owner to confirm",
        commentary: "Risk: generation volume may be mistaken for quality.",
      },
      {
        outcome: "AI outputs requiring significant human correction",
        current: "Data unavailable",
        target: "Target to confirm",
        trend: "Not yet measurable",
        confidence: "Unknown",
        evidence: "Insufficient sample",
        owner: "Owner to confirm",
        commentary: "",
      },
    ],
  },
  {
    group: "Strategic and business impact",
    strategy: "Strategic direction",
    indicators: [
      {
        outcome: "Design-led novel product ideas in flight",
        current: "Data unavailable",
        target: "Contextual target: 5 or more",
        trend: "Not yet measurable",
        confidence: "Unknown",
        evidence: "No comparison group",
        owner: "Owner to confirm",
        commentary: "Attribution to specific capabilities not yet validated.",
      },
      {
        outcome: "Novel ideas shipped with positive KPI impact",
        current: "Data unavailable",
        target: "Contextual target: 2 or more",
        trend: "Not yet measurable",
        confidence: "Unknown",
        evidence: "Confounding factors",
        owner: "Owner to confirm",
        commentary: "Correlation with AI tooling use, not yet causal.",
      },
    ],
  },
];

// One example measurement chain (illustrative only).
const MEASUREMENT_CHAIN_EXAMPLE = {
  capability: "EXAMPLE - UI generation capability (REG-002)",
  steps: [
    { stage: "Investment / capability", detail: "AI-assisted UI generation piloted with a small group of designers." },
    { stage: "Adoption behaviour", detail: "Designers use the capability to draft early UI options faster. Baseline and active-use definition required." },
    { stage: "Workflow change", detail: "Reduced time from kick-off to first prototype. Target and comparison group to confirm." },
    { stage: "Quality or delivery outcome", detail: "Backpack adoption and accessibility of generated UI to be measured. Data source to identify." },
    { stage: "Business contribution", detail: "Not yet measurable. Shared business evidence is required; correlation does not establish causation." },
  ],
};
